<?php
// $Id$

/**
 * Implementation of hook_enable
 */
function menuux_enable() {
  db_query('UPDATE {system} SET weight = 10 WHERE name = "menuux"');
}


/**
 * Implementation of hook_form_alter
 */
function menuux_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'node-form' && user_access('administer menu')) {
    module_load_include('inc', 'menuux', 'menuux.admin');
    menuux_node_form_alter($form, $form_state);
  }
}

/**
 * Implementation of hook_theme
 */
function menuux_theme() {
  return array(
    'menuux_node_form' => array(
      'arguments' => array('form' => array()),
      'file' => 'menuux.admin.inc',
    ),
    'menuux_menu' => array(
      'arguments' => array('menu' => array()),
      'file' => 'menuux.admin.inc',
    )
  );
}

/**
 * Implementation of hook_menu
 */
function menuux_menu() {
  $items = array();
  /*
   * We put the ajax callback under node/add to make sure the right theme will be used
   * In case the site uses an admin theme on the node/add pages...
   */
  $items['node/add/menuux_load_menu/%'] = array(
    'page callback' => 'menuux_load_menu_ajax',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'file' => 'menuux.admin.inc',
    'access callback' => 'menuux_access_menu',
    'access arguments' => array(3),
  );
  return $items;
}

/**
 * Implementation of hook_nodeapi
 */
function menuux_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'validate':
      if (isset($node->fmenu)) {
        module_load_include('inc', 'menuux', 'menuux.admin');
        menuux_node_form_validate($node);
      }
      break;
    case 'insert':
    case 'update':
      if (isset($node->fmenu)) {
        module_load_include('inc', 'menuux', 'menuux.admin');
        menuux_node_form_submit($node);
      }
      break;
    case 'prepare':
      if (isset($node->menu)) {
        $node->fmenu = array();
        if ($node->menu['mlid'] > 0) {
          $node->fmenu['menu_name'] = $node->menu['menu_name'];
          $node->fmenu['mlid'] = $node->menu['mlid'];
          $node->fmenu['plid'] = $node->menu['plid'];
          $node->fmenu['weight'] = $node->menu['weight'];
          $node->fmenu['has_children'] = $node->menu['has_children'];
          $node->fmenu['link_title'] = $node->menu['link_title'];
        }
      }
      break;
  }
}

/**
 * Access callback for ajax menu requests
 *
 * @param string $menu_name
 *  The name of the menu the user is trying to access
 * @return boolean
 *  Does the user have access to the menu or not?
 */
function menuux_access_menu($menu_name) {
  if (!user_access('administer menu')) {
    return FALSE;
  }
  module_load_include('inc', 'menuux', 'menuux.admin');
  $availabe_menus = menuux_available_menus();
  return isset($availabe_menus[$menu_name]);
}